### ISSUE TITLE
#BUG: concurrent.futures

### ISSUE THREAD

**Issue by beyoung** [flopp/GpxTrackPoster#22]
First of all, thanks for your work on this project ,it's great.  #_#. 
but when i cloned this project ,and run my own dataset, bug happened to me, it reported:
```shell 
python create_poster.py --type grid --gpx-dir "data" --year 2018 --title "Running" --athlete "youth" --special 1.gpx --special 2.gpx --special 3.gpx

objc[6009]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called.
objc[6008]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called.
objc[6009]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
objc[6008]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
objc[6007]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called.
Traceback (most recent call last):
  File "create_poster.py", line 165, in <module>
    main()
  File "create_poster.py", line 142, in main
    tracks = loader.load_tracks(args.gpx_dir)
  File "/Users/youth/project/GpxTrackPoster/gpxtrackposter/track_loader.py", line 92, in load_tracks
    loaded_tracks = self._load_tracks(remaining_file_names)
  File "/Users/youth/project/GpxTrackPoster/gpxtrackposter/track_loader.py", line 148, in _load_tracks
    t = future.result()
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```
I don't have any idea where the bug fires.

**Comment by flopp** [comment]
Hmmm, that looks really bad. Seems like the loading of one GPX file crashes the script.
Are you able to run the script on a different set of GPX files?

**Comment by beyoung** [comment]
It runs good when python version is 3.5 .

**Comment by beyoung** [comment]
the GPX files is ok.  
[gpx.tar.gz](https://github.com/flopp/GpxTrackPoster/files/1973373/gpx.tar.gz)

**Comment by flopp** [comment]
Unable to reproduce...
